name: Build and Deploy Flutter Web App to GitHub Pages

on:
  push:
    branches:
      - main  # Deploy when pushing to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.16.9"  # Specify your Flutter version

      - name: Install dependencies
        run: flutter pub get

      - name: Build Flutter Web App
        run: flutter build web --release

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/web  # Directory containing your built web app
          destination_branch: gh-pages  # Deploy to gh-pages branch